name: LiveMap CI

on:
  push:
    branches: 
      - 'master'
      - 'feature/**'
  pull_request:
    branches:
      - 'master'

jobs:
  server:
    name: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/server/App/DasCleverle.DcsExport.LiveMap

      - name: Build
        run: dotnet build --no-restore -c Release
        working-directory: ./src/server/App/DasCleverle.DcsExport.LiveMap

  client:
    name: client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 18.x

      - name: Restore dependencies
        run: npm ci
        working-directory: ./src/server/App/DasCleverle.DcsExport.LiveMap/ClientApp

      - name: Build
        run: npm run build
        working-directory: ./src/server/App/DasCleverle.DcsExport.LiveMap/ClientApp