name: Release GeoJSON lib

on: 
  push:
    tags:
      - 'lib-geojson-v*'

jobs:
  setup:
    uses: ./.github/workflows/get-version.yml
    with:
      ref-prefix: 'lib-geojson-v'

  release:
    needs: setup
    uses: ./.github/workflows/release-lib.yml
    with: 
      project-dir: ./src/lib/DasCleverle.GeoJson
      version: ${{ needs.setup.outputs.version }}
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}