name: Release GeoJSON lib

on: 
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release-lib.yml
    with: 
      project-dir: ./src/lib/DasCleverle.GeoJson
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}