name: Release GeoJSON lib

on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths: 
      - './src/lib/DasCleverle.GeoJson/**'


jobs:
  release:
    uses: ./.github/workflows/release-lib.yml
    with: 
      project-dir: ./src/lib/DasCleverle.GeoJson
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}